server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    root: INFO


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false  # Converts service names to lowercase
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
