server:
  port: 8081

spring:
  application:
    name: account-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      eureka:
        approximateZoneFromHostname: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
  instance:
    preferIpAddress: true


resilience4j:
  circuitbreaker:
    instances:
      addressServiceCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

